---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant
spec:
  source: limitador-operator-catalog
  sourceNamespace: limitador-system
  name: limitador-operator
  channel: "preview"
