# permissions for end users to view ratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimit-viewer-role
rules:
- apiGroups:
  - limitador.kuadrant.io
  resources:
  - ratelimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - limitador.kuadrant.io
  resources:
  - ratelimits/status
  verbs:
  - get
