
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors/finalizers
  verbs:
  - update
- apiGroups:
  - limitador.3scale.net
  resources:
  - limitadors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - limitador.3scale.net
  resources:
  - ratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - limitador.3scale.net
  resources:
  - ratelimits/finalizers
  verbs:
  - update
- apiGroups:
  - limitador.3scale.net
  resources:
  - ratelimits/status
  verbs:
  - get
  - patch
  - update
