name: Limitador-Operator

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: make docker-build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go
      - uses: actions/checkout@v2
      - name: Run the tests
        run: make test
